### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by sanqi** [yinqiwen/ardb#270] opened 2016-07-09 16:33 UTC
hi, i try my mac build ardb, but occur the error
`3 warnings generated.
g++ -o ardb-test  db/rocksdb/rocksdb_engine.o  ../test/test_main.o config.o cron.o logger.o network.o types.o statistics.o  common/channel/channel.o  common/channel/channel_handler_context.o  common/channel/channel_helper.o  common/channel/channel_pipeline.o  common/channel/channel_service.o  common/channel/socket/clientsocket_channel.o  common/channel/socket/datagram_channel.o  common/channel/socket/serversocket_channel.o  common/channel/socket/socket_channel.o  common/channel/fifo/fifo_channel.o  common/channel/codec/delimiter_frame_decoder.o  common/channel/codec/dir_sync_decoder.o  common/channel/codec/int_header_frame_decoder.o  common/channel/codec/redis_command_codec.o  common/channel/codec/redis_reply.o  common/channel/codec/redis_reply_codec.o  common/channel/timer/timer.o  common/channel/timer/timer_channel.o  common/channel/timer/timer_task_queue.o  common/channel/signal/signal_channel.o  common/channel/signal/soft_signal_channel.o  common/util/config_helper.o  common/util/datagram_packet.o  common/util/file_helper.o  common/util/math_helper.o  common/util/mmap.o  common/util/network_helper.o  common/util/socket_address.o  common/util/string_helper.o  common/util/system_helper.o  common/util/time_helper.o  common/util/exception/api_exception.o  common/thread/event_condition.o  common/thread/thread.o  common/coro/coro_channel.o  common/coro/scheduler.o  common/buffer/buffer.o  common/buffer/buffer_helper.o  common/geo/geohash_helper.o  common/util/murmur3.o  common/util/rand.o  common/util/sds.o  common/util/sha1.o  common/coro/coro.o  common/redis/crc64.o  common/redis/endianconv.o  common/redis/intset.o  common/redis/lzf_c.o  common/redis/lzf_d.o  common/redis/ziplist.o  common/redis/zipmap.o  common/geo/geohash.o  common/channel/redis/ae.o  common/channel/redis/zmalloc.o   command/connection.o  command/geo.o  command/hyperloglog.o  command/keys.o  command/lua_scripting.o  command/merge.o  command/migrate.o  command/pubsub.o  command/server.o  command/slowlog.o  command/sort.o  command/t_bitset.o  command/t_hash.o  command/t_list.o  command/t_set.o  command/t_string.o  command/t_zset.o  command/transaction.o  db/codec.o  db/db.o  db/db_utils.o  db/engine.o  repl/master.o  repl/repl.o  repl/slave.o  repl/snapshot.o  repl/swal.o  /www/ardb/src/../deps/rocksdb-4.3.1/librocksdb.a /www/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a /www/ardb/src/../deps/lua/src/liblua.a /www/ardb/src/../deps/jemalloc-4.1.0/lib/libjemalloc.a /www/ardb/src/../deps/snappy-1.1.2/.libs/libsnappy.a -lpthread  -lz -lbz2  
Undefined symbols for architecture x86_64:
  "_LZ4_compressBound", referenced from:
      rocksdb::BlockBasedTableBuilder::WriteBlock(rocksdb::Slice const&, rocksdb::BlockHandle*) in librocksdb.a(block_based_table_builder.o)
  "_LZ4_compressHC2_limitedOutput", referenced from:
      rocksdb::BlockBasedTableBuilder::WriteBlock(rocksdb::Slice const&, rocksdb::BlockHandle*) in librocksdb.a(block_based_table_builder.o)
  "_LZ4_compress_limitedOutput", referenced from:
      rocksdb::BlockBasedTableBuilder::WriteBlock(rocksdb::Slice const&, rocksdb::BlockHandle*) in librocksdb.a(block_based_table_builder.o)
  "_LZ4_decompress_safe", referenced from:
      rocksdb::UncompressBlockContents(char const*, unsigned long, rocksdb::BlockContents*, unsigned int) in librocksdb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test] Error 1`

my mac  is 10.11.5 
`#gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by yinqiwen** [comment] 2016-07-10 12:05
This is a duplicate of #255, u can add -lz4 in the makefile.

**Closed** 2016-09-18 15:14 UTC
